FROM python:3.5-alpine

COPY requirements.txt .

RUN apk add --no-cache --virtual .build-deps gcc musl-dev linux-headers \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps gcc musl-dev linux-headers

WORKDIR /home/bot
 
COPY bot.py .

ENV HOST chat
ENV PORT 5000
ENV REDIS_HOST redis

CMD python bot.py
