version: '3'
services:
  chat:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "80:80"
    environment:
      - PORT=80
  bot:
    build:
      context: .
      dockerfile: 'Dockerfile-bot'
    environment:
      - PORT=80
  redis:
    image: "redis:alpine"
