version: '3'
services:
  chat:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
    environment:
      - PORT=5000
  bot:
    build:
      context: .
      dockerfile: 'Dockerfile-bot'
    depends_on:
      - "chat"
    environment:
      - PORT=5000
  redis:
    image: "redis:alpine"
