version: '3'
services:
  chat:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "5000:5000"
  bot:
    build:
      context: .
      dockerfile: 'Dockerfile-bot'
  redis:
    image: "redis:alpine"
