version: '3'
services:
  chat:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
    environment:
      - PORT=5000
  bot:
    build: .
    command: python bot.py
    depends_on:
      - "chat"
    environment:
      - HOST=chat
      - PORT=5000
  redis:
    image: "redis:alpine"
